logger:
  level: INFO

input:
  generate:
    count: 100
    interval: ""
    mapping: |
      let partition = random_int(min:0,max:9)
      root = {
        "key": {
          "id": random_int(min:5000,max:10000),
        },
        "name": fake("name"),
        "score": random_int(max:1000000),
        "url": fake("url"),
        "metadata": {
          "partition": $partition,
          "offset": count($partition.string()),
          "timestamp": timestamp_unix_micro().int64(),
          "is_tombstone": random_int(min:0,max:1).bool()
        }
      }

pipeline:
  threads: 1

output:
  bqwrite:
    project: "${BQ_PROJECT}"
    dataset: "${BQ_DATASET}"
    table: "${BQ_TABLE}"
    protobuf_path: "./protos"
    protobuf_name: com.Entity
    batching:
      period: 10s
